# Ch2 Numpy基本運算函式

## 2-1 陣列重塑-reshape()、resize()

In [2]:
import numpy as np

a = np.arange(12)
print(a)

print(a.reshape(3, 4))

b = np.reshape(a, (3, 4))
b

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
b[0, 1] = 0
print(b)
print(a)

[[ 0  0  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  0  2  3  4  5  6  7  8  9 10 11]


In [4]:
print(id(a))
print(id(b))

2384727955216
2384732123376


In [5]:
c = np.arange(12)

d = np.reshape(c, (3, 4), order = "C")
print(d)
d = np.reshape(c, (3, 4), order = "F")
d

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [6]:
# np.reshape(c, (3, 5))
a = np.arange(12)
print(np.reshape(a, (3, -1)))
np.reshape(a, (-1, 6))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [7]:
a = np.arange(12).reshape((3, 4))
print(a)
b = np.arange(12).reshape((3, -1))
print(b)
c = np.arange(15).reshape((3, 4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


ValueError: cannot reshape array of size 15 into shape (3,4)

In [ ]:
a = np.arange(12)
print(np.reshape(a, (3, 4)))
print(np.resize(a, (3, 5)))
np.resize(a, (3, 2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11  0  1  2]]


array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b = np.resize(a, (3, 4))
b[0, 1] = 0
print(b)
print(a)
print(id(a), id(b))

[[ 0  0  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
1562736598480 1562736605104


## 2-2 在陣列最後面加入元素

In [ ]:
import numpy as np

a = np.arange(12)
print(np.append(a, [6, 4, 2]))

b = np.arange(12).reshape((3, 4))
print(b)

np.append(b, [1, 2, 3, 4])


[ 0  1  2  3  4  5  6  7  8  9 10 11  6  4  2]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  2,  3,  4])

In [ ]:
print(b)
print(np.append(b, [[12, 13, 14, 15]], axis = 0))
np.append(b, [12, 13, 14, 15], axis = 0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
c = np.arange(12).reshape((3, 4))
print(c)
print(np.append(c, [[6], [6], [6]], axis = 1))
d = np.linspace(0, 26, 12).reshape((3, 4))
print(d)
print(np.append(c, d, axis = 0))
np.append(c, d, axis = 1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  6]
 [ 4  5  6  7  6]
 [ 8  9 10 11  6]]
[[ 0.          2.36363636  4.72727273  7.09090909]
 [ 9.45454545 11.81818182 14.18181818 16.54545455]
 [18.90909091 21.27272727 23.63636364 26.        ]]
[[ 0.          1.          2.          3.        ]
 [ 4.          5.          6.          7.        ]
 [ 8.          9.         10.         11.        ]
 [ 0.          2.36363636  4.72727273  7.09090909]
 [ 9.45454545 11.81818182 14.18181818 16.54545455]
 [18.90909091 21.27272727 23.63636364 26.        ]]


array([[ 0.        ,  1.        ,  2.        ,  3.        ,  0.        ,
         2.36363636,  4.72727273,  7.09090909],
       [ 4.        ,  5.        ,  6.        ,  7.        ,  9.45454545,
        11.81818182, 14.18181818, 16.54545455],
       [ 8.        ,  9.        , 10.        , 11.        , 18.90909091,
        21.27272727, 23.63636364, 26.        ]])

In [ ]:
print(np.array([[6], [6], [6]]).shape)
np.array([[1, 2, 3]]).shape

(3, 1)


(1, 3)

## 2-3 判斷陣列真假值-all()與any()

In [ ]:
import numpy as np

a = np.array([
    [1, 1, 1], 
    [1, 0, 1], 
    [1, 0, 1]
])
print(np.all(a))

b = np.ones((3, 3))
print(b)
print(np.all(b))
print(np.all(a < 2))
print(np.all(b % 3 == 1))
print(np.all(a, axis = 0))
print(np.all(a, axis = 1))

False
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
True
True
True
[ True False  True]
[ True False False]


In [ ]:
print(np.all(a, axis = 0, keepdims = True))
print(a.all())
print(b.all())
print(a.all(axis = 1))
print(a < 2)
print((a < 2).all())
a.all(keepdims = True)

[[ True False  True]]
False
True
[ True False False]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
True


array([[False]])

In [ ]:
a = np.random.randint(10, size = (2, 3)) # 數字有可能重複
print(a)
print(np.any(a == 9))
print(np.any(a == 5))
print(np.any(a % 2 == 0, axis = 0))
print(np.any(a % 2 == 1, axis = 1))

[[6 0 0]
 [8 9 2]]
True
False
[ True  True  True]
[False  True]


In [ ]:
print(np.any(a % 2 == 1, axis = 1, keepdims = True))
print(np.any(a > 2, keepdims = True))

[[False]
 [ True]]
[[ True]]


In [ ]:
print((a % 5 == 0).any())
print((a > 3).any())
b = np.random.randint(10, size = (2, 3))
print(b)
print((a == b).any(axis = 1))
print((a == b).any(axis = 1, keepdims = True))

True
True
[[2 0 8]
 [3 4 8]]
[ True False]
[[ True]
 [False]]


## 2-4 找出符合條件的元素-where()

In [ ]:
a = np.arange(20, 0, -2)
print(a)
print(np.where(a < 10))
a[np.where(a < 10)] # 也可以加[0]將位置取出來

[20 18 16 14 12 10  8  6  4  2]
(array([6, 7, 8, 9], dtype=int64),)


array([8, 6, 4, 2])

In [ ]:
a = np.arange(12).reshape((3, 4))
print(a)
print(np.where(a % 2 == 0))
a[np.where(a % 2 == 0)]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(array([0, 0, 1, 1, 2, 2], dtype=int64), array([0, 2, 0, 2, 0, 2], dtype=int64))


array([ 0,  2,  4,  6,  8, 10])

In [ ]:
print(np.where(a % 2 == 0, "even", "odd"))
print(a)
# np.where(a % 2 == 0, "even")
b = np.reshape(a, (3, 4))
print(b)
c = b ** 2
print(c)
np.where(b % 2 == 0, b, c)

[['even' 'odd' 'even' 'odd']
 ['even' 'odd' 'even' 'odd']
 ['even' 'odd' 'even' 'odd']]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


array([[  0,   1,   2,   9],
       [  4,  25,   6,  49],
       [  8,  81,  10, 121]])

## 2-5 取出最大值、最小值-amax()與amin()

In [ ]:
import numpy as np

np.amax(np.array([1, 2, 3, 2, 1]))

3

In [ ]:
arr = np.array([1, 2, 3, 4]).reshape((2, 2))
print(arr)
print(np.amax(arr, axis = 0))
print(np.amax(arr, axis = 1))
np.amax(arr, keepdims = True)

[[1 2]
 [3 4]]
[3 4]
[2 4]


array([[4]])

In [ ]:
b = np.random.randint(30, size = (2, 3, 5))
print(b)
print(b.max(axis = 0))
print(b.max(axis = 1))
print(b.max(axis = 2))

[[[ 7 13 25 16 11]
  [ 0 25 14 11  9]
  [15  6  8  6 17]]

 [[29 12 22 19 17]
  [ 3 15 27  0 26]
  [ 6  4  6 25 10]]]
[[29 13 25 19 17]
 [ 3 25 27 11 26]
 [15  6  8 25 17]]
[[15 25 25 16 17]
 [29 15 27 25 26]]
[[25 25 17]
 [29 27 25]]


In [ ]:
a = np.array([
    [1.2, 1.3, 0.1, 1.5], 
    [2.1, 0.2, 0.3, 2.0], 
    [0.1, 0.5, 0.5, 2.3]
])
print(a)
print(np.amin(a))
print(np.amin(a, axis = 0))
print(np.amin(a, axis = 1))
print(np.amin(a, axis = 0, keepdims = True))
print(np.amin(a, axis = 1, keepdims = True))

[[1.2 1.3 0.1 1.5]
 [2.1 0.2 0.3 2. ]
 [0.1 0.5 0.5 2.3]]
0.1
[0.1 0.2 0.1 1.5]
[0.1 0.2 0.1]
[[0.1 0.2 0.1 1.5]]
[[0.1]
 [0.2]
 [0.1]]


## 2-6 取出最大值、最小值的索引位置-argmax()、argmin()

In [ ]:
import numpy as np

a = np.random.randint(10, size = 10)
print(a)
print(np.argmax(a))
print(a.argmax())

[2 5 7 8 6 2 6 1 9 6]
8
8


In [ ]:
b = np.random.randint(10, size = (3, 4))
print(b)
print(np.argmax(b))
print(np.argmax(b, axis = 0))
print(np.argmax(b, axis = 1))

[[7 8 2 9]
 [4 1 2 6]
 [6 8 8 0]]
3
[0 0 2 0]
[3 3 1]


In [ ]:
c = np.random.randint(10, size = (2, 3, 4))
print(c)
print(np.argmax(c, axis = 0))
print(np.argmax(c, axis = 1))
print(np.argmax(c, axis = 2))

[[[0 1 3 3]
  [9 0 7 8]
  [5 3 4 6]]

 [[5 9 9 3]
  [5 1 7 4]
  [7 3 2 3]]]
[[1 1 1 0]
 [0 1 0 0]
 [1 0 0 0]]
[[1 2 1 1]
 [2 0 0 1]]
[[2 0 3]
 [1 2 0]]


In [ ]:
d = np.array([
    [1.2, 1.5, 2.3, 1.8], 
    [0.2, 2.5, 2.1, 2.0], 
    [3.1, 3.3, 1.5, 2.1]
])
print(d)
print(np.argmin(d))
print(np.argmin(d, axis = 0))
print(np.argmin(d, axis = 1))
print(d.argmin(axis = 1))

[[1.2 1.5 2.3 1.8]
 [0.2 2.5 2.1 2. ]
 [3.1 3.3 1.5 2.1]]
4
[1 0 2 0]
[0 0 2]
[0 0 2]


## 2-7 陣列轉置-transpose()


In [8]:
import numpy as np

a = np.arange(12).reshape((3, 4))
print(a)
print(np.transpose(a))
print(np.transpose(a, axes = (1, 0))) # 不寫axes = 也可以

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [9]:
b = np.arange(6)
print(b)
print(np.transpose(b))
print(b.shape)
b = b.reshape((1, 6))
print(b)
print(np.transpose(b))

[0 1 2 3 4 5]
[0 1 2 3 4 5]
(6,)
[[0 1 2 3 4 5]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [10]:
c = np.arange(24).reshape((4, 3, 2))
print(c)
print(np.transpose(c))
print(np.transpose(c, axes = (1, 0, 2)))

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
[[[ 0  6 12 18]
  [ 2  8 14 20]
  [ 4 10 16 22]]

 [[ 1  7 13 19]
  [ 3  9 15 21]
  [ 5 11 17 23]]]
[[[ 0  1]
  [ 6  7]
  [12 13]
  [18 19]]

 [[ 2  3]
  [ 8  9]
  [14 15]
  [20 21]]

 [[ 4  5]
  [10 11]
  [16 17]
  [22 23]]]


In [14]:
print(c.transpose())
print(c.shape)
print(c.transpose().shape)
print(c.transpose((1, 0, 2)))
print(c.transpose((1, 0, 2)).shape)

[[[ 0  6 12 18]
  [ 2  8 14 20]
  [ 4 10 16 22]]

 [[ 1  7 13 19]
  [ 3  9 15 21]
  [ 5 11 17 23]]]
(4, 3, 2)
(2, 3, 4)
[[[ 0  1]
  [ 6  7]
  [12 13]
  [18 19]]

 [[ 2  3]
  [ 8  9]
  [14 15]
  [20 21]]

 [[ 4  5]
  [10 11]
  [16 17]
  [22 23]]]
(3, 4, 2)


In [12]:
print(a)
print(a.T)
print(b)
print(b.T)
print(c)
print(c.T)
print(a.transpose().shape == a.T.shape)
print(b.transpose().shape == b.T.shape)
print(np.transpose(c).shape == c.T.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[0 1 2 3 4 5]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
[[[ 0  6 12 18]
  [ 2  8 14 20]
  [ 4 10 16 22]]

 [[ 1  7 13 19]
  [ 3  9 15 21]
  [ 5 11 17 23]]]
True
True
True


## 2-8 陣列排序-sort()與argsort()

In [22]:
import numpy as np

a = np.random.randint(0, 100, size = 20)
print(a)
print(np.sort(a))
a = np.array([1, 3, 2])
print(a)
print(np.argsort(a))

[24 54 83 92 57 75 96 82 73 91 97 49 37 37 38  6 30 90 39 89]
[ 6 24 30 37 37 38 39 49 54 57 73 75 82 83 89 90 91 92 96 97]
[1 3 2]
[0 2 1]


In [27]:
b = np.random.randint(0, 100, size = 20).reshape((4, 5))
print(b)
print(np.sort(b))
print(np.argsort(b))
print(np.sort(b, axis = 0))
print(np.argsort(b, axis = 0))

[[15 76 77 22 40]
 [63 33 45 95 15]
 [80 28 71 75 48]
 [90 97 48  1 28]]
[[15 22 40 76 77]
 [15 33 45 63 95]
 [28 48 71 75 80]
 [ 1 28 48 90 97]]
[[0 3 4 1 2]
 [4 1 2 0 3]
 [1 4 2 3 0]
 [3 4 2 0 1]]
[[15 28 45  1 15]
 [63 33 48 22 28]
 [80 76 71 75 40]
 [90 97 77 95 48]]
[[0 2 1 3 1]
 [1 1 3 0 3]
 [2 0 2 2 0]
 [3 3 0 1 2]]


In [30]:
c = np.random.randint(0, 100, size = (2, 4, 5))
print(c)
print(np.sort(c, axis = 0))
print(np.argsort(c, axis = 0))

[[[70 59 35 63 72]
  [90 93  9 83 22]
  [13 41 78 55 65]
  [80 69 94 55 31]]

 [[66 40 52 96 13]
  [85 40  6 34 17]
  [79 49 27 66 21]
  [72  2 76 64 91]]]
[[[66 40 35 63 13]
  [85 40  6 34 17]
  [13 41 27 55 21]
  [72  2 76 55 31]]

 [[70 59 52 96 72]
  [90 93  9 83 22]
  [79 49 78 66 65]
  [80 69 94 64 91]]]
[[[1 1 0 0 1]
  [1 1 1 1 1]
  [0 0 1 0 1]
  [1 1 1 0 0]]

 [[0 0 1 1 0]
  [0 0 0 0 0]
  [1 1 0 1 0]
  [0 0 0 1 1]]]


In [55]:
values = [("Alice", 25, 9.7), ("Bob", 12, 7.6), ("Catherine", 1, 8.6), ("David", 10, 7.6)]
dt = [("name", "S10"), ("ID", int), ("score", float)]
a = np.array(values, dtype = dt)
print(a)
print(np.sort(a, order = "score"))
print(np.argsort(a, order = "score"))
print(np.sort(a, order = ["score", "ID"]))

[(b'Alice', 25, 9.7) (b'Bob', 12, 7.6) (b'Catherine',  1, 8.6)
 (b'David', 10, 7.6)]
[(b'Bob', 12, 7.6) (b'David', 10, 7.6) (b'Catherine',  1, 8.6)
 (b'Alice', 25, 9.7)]
[1 3 2 0]
[(b'David', 10, 7.6) (b'Bob', 12, 7.6) (b'Catherine',  1, 8.6)
 (b'Alice', 25, 9.7)]


In [42]:
a = np.random.randint(0, 100, size = 20) # 不用size也可以
print(a)
print(np.sort(a))
print(a)
print(a.sort())
print(a)

[86 95 90  1 57 38 53 10 82  2 59  4 30 98 54 49 48 34 29 71]
[ 1  2  4 10 29 30 34 38 48 49 53 54 57 59 71 82 86 90 95 98]
[86 95 90  1 57 38 53 10 82  2 59  4 30 98 54 49 48 34 29 71]
None
[ 1  2  4 10 29 30 34 38 48 49 53 54 57 59 71 82 86 90 95 98]


## 2-9 陣列合併-hstack()與vstack()

In [53]:
a = np.array([1, 2, 3])
b = np.array([4, 5])
np.append(a, b)
c = [1, 2, 3]
d = [4, 5]
c + d

[1, 2, 3, 4, 5]

In [59]:
import numpy as np

a = np.arange(12)
b = np.arange(2)
print(a)
print(b)
np.hstack((a, b))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[0 1]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1])

In [74]:
c = np.arange(4).reshape((2, 2))
print(c)
# print(np.hstack((a, c)))
d = np.arange(6).reshape((2, 3))
print(d)
print(np.hstack((c, d)))
np.append(arr = c, values = d, axis = 1)

[[0 1]
 [2 3]]
[[0 1 2]
 [3 4 5]]
[[0 1 0 1 2]
 [2 3 3 4 5]]


array([[0, 1, 0, 1, 2],
       [2, 3, 3, 4, 5]])

In [66]:
e = np.arange(12).reshape((2, 2, 3))
f = np.arange(6).reshape((2, 1, 3))
print(e)
print(f)
np.hstack((e, f))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[0 1 2]]

 [[3 4 5]]]


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 0,  1,  2]],

       [[ 6,  7,  8],
        [ 9, 10, 11],
        [ 3,  4,  5]]])

In [68]:
a = np.arange(6).reshape((2, 3))
b = np.arange(8).reshape((4, 2))
print(a)
print(b)
print(np.hstack((a, b)))

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 4

In [79]:
a = np.arange(12).reshape((-1, 1))
b = np.arange(2).reshape((-1, 1))
print(a)
print(b)
print(np.vstack((a, b)))
c = np.arange(2).reshape((1, 2))
print(c)
# np.vstack((a, c))
d = np.arange(4).reshape((2, 2))
print(d)
np.vstack((c, d))

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
[[0]
 [1]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [ 0]
 [ 1]]
[[0 1]]
[[0 1]
 [2 3]]


array([[0, 1],
       [0, 1],
       [2, 3]])

In [86]:
e = np.arange(24).reshape((4, 3, 2))
f = np.arange(6).reshape((1, 3, 2))
print(e)
print(f)
g = np.vstack((e, f))
print(g)
g.shape

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
[[[0 1]
  [2 3]
  [4 5]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]

 [[ 0  1]
  [ 2  3]
  [ 4  5]]]


(5, 3, 2)

## 2-10 建立元素都是0的陣列-zeros()

In [110]:
import numpy as np

print(np.zeros(10))
print(np.zeros(10, dtype = int))
print(np.zeros(shape = (3, 4))) # 不用打shape也可以

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [112]:
a = np.arange(12).reshape((3, 4))
print(a)
print(np.zeros(a.shape))
print(np.zeros_like(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [92]:
a = np.arange(12).reshape((3, 4))
print(a)
b = np.zeros(a.shape)
print(b)
c = np.zeros_like(a)
c

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## 2-11 建立元素都是1的陣列-ones()

In [114]:
import numpy as np

np.ones(1) / 10

array([0.1])

In [99]:
import numpy as np

print(np.ones(3))
print(np.ones((2, 3)))
print(np.ones(4, dtype = np.int8))

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 1 1 1]


In [115]:
a = np.array([[1, 2, 3], [2, 3, 4]])
print(a)
print(np.ones_like(a))
b = np.array([2, 3, 4], dtype = "int8")
print(b)
print(np.ones(b.shape))
np.ones_like(b)

[[1 2 3]
 [2 3 4]]
[[1 1 1]
 [1 1 1]]
[2 3 4]
[1. 1. 1.]


array([1, 1, 1], dtype=int8)

In [116]:
a = np.arange(6).reshape((2, 3))
print(a)
b = np.ones_like(a)
print(b) # ones_like的型別會和a一樣，ones則是預設浮點數
c = np.ones(a.shape)
c

[[0 1 2]
 [3 4 5]]
[[1 1 1]
 [1 1 1]]


array([[1., 1., 1.],
       [1., 1., 1.]])

## 2-12 建立「不限定元素值」的陣列-empty()

In [137]:
import numpy as np

print(np.empty(15))
print(np.empty((2, 3)))
print(np.empty((2, 2, 4)))

[5.43230922e-312 0.00000000e+000 7.29112202e-304 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 4.94065646e-324
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 5.43230922e-312]
[[6.95220731e-310 4.94065646e-324 6.95220733e-310]
 [1.42173718e-312 2.16939877e-317 4.94065646e-324]]
[[[4.67296746e-307 1.69121096e-306 8.45599366e-307 1.11256817e-306]
  [1.06811422e-306 1.42417221e-306 1.11260619e-306 8.90094053e-307]]

 [[1.86919378e-306 1.06809792e-306 1.37962456e-306 1.69111861e-306]
  [1.78020169e-306 1.37961777e-306 7.56599807e-307 7.56599806e-307]]]


In [140]:
%timeit np.zeros(10000)
%timeit np.ones(10000)
%timeit np.empty(10000)

2.96 µs ± 19.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
4.72 µs ± 126 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
643 ns ± 17.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


## 2-13 建立指定範圍的等差陣列-arange()

In [148]:
import numpy as np

print(np.arange(5))
print(np.arange(-10))
print(np.arange(stop = 4.5))

[0 1 2 3 4]
[]
[0. 1. 2. 3. 4.]


In [10]:
print(np.arange(1, 8))
print(np.arange(2, 10))
print(np.arange(0.5, 5.5))
print(np.arange(0.55, 5.55))

[1 2 3 4 5 6 7]
[2 3 4 5 6 7 8 9]
[0.5 1.5 2.5 3.5 4.5]
[0.55 1.55 2.55 3.55 4.55]


In [156]:
print(np.arange(2, 12, 2))
print(np.arange(2, 5, 0.2))
print(np.arange(5, 2, -1))
np.arange(stop = 3, step = 1)

[ 2  4  6  8 10]
[2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4 4.6 4.8]
[5 4 3]


array([0, 1, 2])

In [8]:
import numpy as np

print(np.arange(5, dtype = "float64"))
print(np.arange(5.0, dtype = "int"))
print(np.arange(0, 5, 0.5, dtype = "int"))
np.arange(0, 5, 1.5, dtype = "int")

[0. 1. 2. 3. 4.]
[0 1 2 3 4]
[0 0 0 0 0 0 0 0 0 0]


array([0, 1, 2, 3])

## 2-14 建立指定範圍的等差數列-linspace()

In [1]:
import numpy as np
np.arange(10).reshape((2, 5)).argmax(-1) # 這邊-1和1的結果是一樣的

array([4, 4], dtype=int64)

In [2]:
import numpy as np

np.linspace(0, -1, retstep = True)

(array([ 0.        , -0.02040816, -0.04081633, -0.06122449, -0.08163265,
        -0.10204082, -0.12244898, -0.14285714, -0.16326531, -0.18367347,
        -0.20408163, -0.2244898 , -0.24489796, -0.26530612, -0.28571429,
        -0.30612245, -0.32653061, -0.34693878, -0.36734694, -0.3877551 ,
        -0.40816327, -0.42857143, -0.44897959, -0.46938776, -0.48979592,
        -0.51020408, -0.53061224, -0.55102041, -0.57142857, -0.59183673,
        -0.6122449 , -0.63265306, -0.65306122, -0.67346939, -0.69387755,
        -0.71428571, -0.73469388, -0.75510204, -0.7755102 , -0.79591837,
        -0.81632653, -0.83673469, -0.85714286, -0.87755102, -0.89795918,
        -0.91836735, -0.93877551, -0.95918367, -0.97959184, -1.        ]),
 -0.02040816326530612)

In [24]:
import numpy as np

print(np.linspace(0, 1))
print(len(np.linspace(0, 1)))
1 / (50 - 1)

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]
50


0.02040816326530612

In [28]:
print(np.linspace(0, 49))
print(np.linspace(0, 2, 3))
print(np.linspace(0, -2, 3))
print(np.linspace(0, 2, num = 3))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]
[0. 1. 2.]
[ 0. -1. -2.]
[0. 1. 2.]


In [31]:
print(np.linspace(0, 2, num = 3, endpoint = False))
print((2 - 0) / 3) # 元素變四個、切三刀、取前三個的概念
np.linspace(0, 2, num = 3, endpoint = True)

[0.         0.66666667 1.33333333]
0.6666666666666666


array([0., 1., 2.])

In [35]:
print(np.linspace(0, 1, retstep = True))
print(np.linspace(0, 2, num = 3, retstep = True))
np.linspace(0, 2, num = 3, retstep = False)

(array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ]), 0.02040816326530612)
(array([0., 1., 2.]), 1.0)


array([0., 1., 2.])

In [36]:
np.linspace(-4, 4, 100, retstep = True)

(array([-4.        , -3.91919192, -3.83838384, -3.75757576, -3.67676768,
        -3.5959596 , -3.51515152, -3.43434343, -3.35353535, -3.27272727,
        -3.19191919, -3.11111111, -3.03030303, -2.94949495, -2.86868687,
        -2.78787879, -2.70707071, -2.62626263, -2.54545455, -2.46464646,
        -2.38383838, -2.3030303 , -2.22222222, -2.14141414, -2.06060606,
        -1.97979798, -1.8989899 , -1.81818182, -1.73737374, -1.65656566,
        -1.57575758, -1.49494949, -1.41414141, -1.33333333, -1.25252525,
        -1.17171717, -1.09090909, -1.01010101, -0.92929293, -0.84848485,
        -0.76767677, -0.68686869, -0.60606061, -0.52525253, -0.44444444,
        -0.36363636, -0.28282828, -0.2020202 , -0.12121212, -0.04040404,
         0.04040404,  0.12121212,  0.2020202 ,  0.28282828,  0.36363636,
         0.44444444,  0.52525253,  0.60606061,  0.68686869,  0.76767677,
         0.84848485,  0.92929293,  1.01010101,  1.09090909,  1.17171717,
         1.25252525,  1.33333333,  1.41414141,  1.4

## 2-15 建立單位矩陣-eye()與identity()

In [17]:
np.matrix(np.arange(10).reshape(2, 5)) # 會變成matrix而不是array

matrix([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [5]:
import numpy as np

print(np.eye(3))
np.eye(10)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [7]:
print(np.eye(2, 3))
np.eye(5, 4)

[[1. 0. 0.]
 [0. 1. 0.]]


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [11]:
print(np.eye(5, k = 0))
print(np.eye(5, k = 1))
print(np.eye(5, k = -1))
np.eye(5, k = 3)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
print(np.identity(5))
np.identity(2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


array([[1., 0.],
       [0., 1.]])

In [14]:
%timeit np.eye(10000)
%timeit np.identity(10000)

21 ms ± 1.16 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
21.2 ms ± 962 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


## 2-16 將陣列展平為1D陣列-flatten()

In [23]:
a = np.array([1, 2, 3])
b = a.copy()
a[0] = 4
b

array([1, 2, 3])

In [32]:
import numpy as np

a = np.arange(10).reshape((2, 5))
print(a)
b = a.flatten()
print(a)
print(b)
print(a.shape)
b.shape

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
(2, 5)


(10,)

In [28]:
c = np.arange(12).reshape((2, 2, 3))
print(c)
d = c.flatten()
print(c)
print(d)
print(c.shape)
d.shape

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(2, 2, 3)


(12,)

## 2-17 將陣列展平為1D陣列-ravel()

In [38]:
a = np.arange(10).reshape((2, 5))
print(a.reshape((1, 10)))
print(a)
print(a.resize((1, 10)))
a

[[0 1 2 3 4 5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
None


array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [43]:
import numpy as np

a = np.arange(10).reshape((2, 5))
print(a)
print(a.ravel())
print(np.ravel(a))
a

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [47]:
print(a)
print(a.ravel(order = "C"))
a.ravel(order = "F")

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


array([0, 5, 1, 6, 2, 7, 3, 8, 4, 9])

In [53]:
b = np.arange(10).reshape((2, 5), order = "F")
print(b)
print(b.ravel(order = "F"))
print(b.ravel(order = "A"))
b.ravel()

[[0 2 4 6 8]
 [1 3 5 7 9]]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


array([0, 2, 4, 6, 8, 1, 3, 5, 7, 9])

## 2-18 找出不是0的元素-nonzero()

In [57]:
print(a != 0)
print(np.where(a != 0))

[[False  True  True  True  True]
 [ True  True  True  True  True]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 1], dtype=int64), array([1, 2, 3, 4, 0, 1, 2, 3, 4], dtype=int64))


In [6]:
import numpy as np

a = np.random.randint(0, 10, size = 20)
print(a)
print(np.nonzero(a))
print(a.nonzero())
a[np.nonzero(a)]

[9 8 9 0 6 1 9 6 5 0 0 7 2 7 2 4 8 5 6 6]
(array([ 0,  1,  2,  4,  5,  6,  7,  8, 11, 12, 13, 14, 15, 16, 17, 18, 19],
      dtype=int64),)
(array([ 0,  1,  2,  4,  5,  6,  7,  8, 11, 12, 13, 14, 15, 16, 17, 18, 19],
      dtype=int64),)


array([9, 8, 9, 6, 1, 9, 6, 5, 7, 2, 7, 2, 4, 8, 5, 6, 6])

In [12]:
b = np.random.randint(0, 10, size = (4, 5))
print(b)
print(np.nonzero(b))
print(b.nonzero())
b[b.nonzero()]

[[6 5 4 7 4]
 [2 7 2 0 8]
 [7 1 9 4 0]
 [4 7 6 7 4]]
(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3], dtype=int64), array([0, 1, 2, 3, 4, 0, 1, 2, 4, 0, 1, 2, 3, 0, 1, 2, 3, 4], dtype=int64))
(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3], dtype=int64), array([0, 1, 2, 3, 4, 0, 1, 2, 4, 0, 1, 2, 3, 0, 1, 2, 3, 4], dtype=int64))


array([6, 5, 4, 7, 4, 2, 7, 2, 8, 7, 1, 9, 4, 4, 7, 6, 7, 4])

## 2-19 複製陣列元素，拼貼成新陣列-tile()

In [2]:
import numpy as np

a = np.array([0, 1, 2])
print(a)
print(np.tile(a, 2))

[0 1 2]
[0 1 2 0 1 2]


In [3]:
np.tile(a, (3, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [4]:
np.tile(a, (2, 3, 4))

array([[[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]]])

## 2-20 增加陣列的軸數-np.newaxis物件

In [30]:
import numpy as np

print(np.newaxis == None)
x = np.arange(15).reshape((3, 5))
print(x)
print(x[np.newaxis, :, : ])
print(x[:, np.newaxis, : ])
print(x[:, None, : ])
x = x.flatten()
print(x)
print(x[:, np.newaxis])
x[:, np.newaxis].shape


True
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]
[[[ 0  1  2  3  4]]

 [[ 5  6  7  8  9]]

 [[10 11 12 13 14]]]
[[[ 0  1  2  3  4]]

 [[ 5  6  7  8  9]]

 [[10 11 12 13 14]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]]


(15, 1)

In [22]:
x = np.arange(15).reshape((3, 5))
print(x)
print(np.reshape(x, (1, 3, 5)))
print(np.reshape(x, (3, 1, 5)))
x = x.flatten()
np.reshape(x, (-1, 1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]
[[[ 0  1  2  3  4]]

 [[ 5  6  7  8  9]]

 [[10 11 12 13 14]]]


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

## 2-21 陣列合併-np.r_與np.c_物件

In [5]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.r_[a, b])
print(np.r_[2, 5, 3, np.array([2, 3]), 4.2])
c = np.zeros((2, 3))
d = np.ones((3, 3))
print(np.r_[c, d])
d = np.ones((3, 4))
# np.r_[c, d]

[1 2 3 4 5 6]
[2.  5.  3.  2.  3.  4.2]
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
a = np.ones((2, 2))
b = np.zeros((2, 2))
print(np.r_["1", a, b])
print(np.r_["1", a, b].shape)
print(np.r_["0", a, b])
print(np.r_["0", a, b].shape)
np.r_[a, b].shape

[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
(2, 4)
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
(4, 2)


(4, 2)

In [39]:
c = np.ones((2, 2, 2))
d = np.zeros((2, 2, 2))
print(c)
print(d)
print(np.r_["0", c, d])
print(np.r_["1", c, d])
print(np.r_["2", c, d])
print(np.r_["0", c, d].shape)
print(np.r_["1", c, d].shape)
print(np.r_["2", c, d].shape)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
[[[1. 1.]
  [1. 1.]
  [0. 0.]
  [0. 0.]]

 [[1. 1.]
  [1. 1.]
  [0. 0.]
  [0. 0.]]]
[[[1. 1. 0. 0.]
  [1. 1. 0. 0.]]

 [[1. 1. 0. 0.]
  [1. 1. 0. 0.]]]
(4, 2, 2)
(2, 4, 2)
(2, 2, 4)


In [20]:
print(np.r_["0, 2", [0, 1, 2], [3, 3, 3]])
np.r_["0, 2", [0, 1, 2], [3, 3, 3]].shape

[[0 1 2]
 [3 3 3]]


(2, 3)

In [35]:
print(np.r_["0, 3", [0, 1, 2], [3, 3, 3]])
np.r_["0, 3", [0, 1, 2], [3, 3, 3]].shape

[[[0 1 2]]

 [[3 3 3]]]


(2, 1, 3)

In [29]:
print(np.r_["0, 2, -1", [0, 1, 2], [3, 3, 3]])
print(np.r_["0, 2, -1", [0, 1, 2], [3, 3, 3]].shape)
print(np.r_["0, 2, 0", [0, 1, 2], [3, 3, 3]])
print(np.r_["0, 2, 0", [0, 1, 2], [3, 3, 3]].shape)
print(np.r_["0, 3, 0", [0, 1, 2], [3, 3, 3]])
print(np.r_["0, 3, 0", [0, 1, 2], [3, 3, 3]].shape)

[[0 1 2]
 [3 3 3]]
(2, 3)
[[0]
 [1]
 [2]
 [3]
 [3]
 [3]]
(6, 1)
[[[0]]

 [[1]]

 [[2]]

 [[3]]

 [[3]]

 [[3]]]
(6, 1, 1)


In [44]:
print(np.r_[0: 10])
print(np.r_[: 10])
print(np.r_[0: 10: 2])
print(np.r_[10: 0: -1])
np.r_[0: 10, 0, 4, np.array([3, 3])]

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[10  9  8  7  6  5  4  3  2  1]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 4, 3, 3])

In [48]:
a = np.array([1, 4, 6])
b = np.array([2, 2, 2])
print(np.r_["r", a, b])
print(np.r_["c", a, b])
c = np.ones((4, 5))
d = np.zeros((2, 5))
print(np.r_["r", c, d])
np.r_["c", c, d]

[[1 4 6 2 2 2]]
[[1]
 [4]
 [6]
 [2]
 [2]
 [2]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


matrix([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [4]:
a = np.ones((3, 2))
b = np.zeros((3, 3))
print(a)
print(b)
print(np.c_[a, b])
c = np.zeros(3)
print(c)
print(np.c_[a, c])
print(np.c_[a, c].shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]]
[0. 0. 0.]
[[1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]]
(3, 3)


## 2-22 陣列的儲存與讀取-save()與load()

In [20]:
import numpy as np

a = np.random.randn(1200 * 1000).reshape(1200, -1) # randn就是以0為中心、標準差為1，所以會有正負數 # rand則是0~1
np.save("a.npy", a)
print(np.load("a.npy"))
c = np.random.randn(12 * 20 * 40).reshape((12, 20, 40))
np.save("c.npy", c)
d = np.load("c.npy")
d.shape

[[ 1.59381442  0.71749376  0.46432964 ...  1.10729264 -0.12092493
   0.03225502]
 [ 0.49782159 -0.24461332  0.47723178 ... -0.03223724 -0.7591109
  -0.39976959]
 [ 0.74044124 -0.36142158  0.22600279 ...  0.68022331  0.18171827
  -1.01056732]
 ...
 [-0.7166352  -0.67839424 -0.38216139 ...  0.64734888  0.6943135
  -0.50653059]
 [-0.4485594  -1.14298355  0.20031743 ...  0.92012527 -0.56289976
   1.62570411]
 [ 1.0369156  -0.35254679  0.1180715  ... -1.02090399 -1.38446189
  -2.65322767]]


(12, 20, 40)

## 2-23 以文字格式儲存、讀取陣列內容-savetxt()與loadtxt()

In [4]:
import numpy as np

a = np.random.randn(3, 4)
np.savetxt("sample1.txt", a)
b = np.loadtxt("sample1.txt")
print(a)
print(b)
np.savetxt("sample1.csv", a)
c = np.loadtxt("sample1.csv")
c

[[ 1.01728634  1.51464919 -0.24714715 -0.54425527]
 [ 0.24253792 -0.83579983  0.41615418 -1.66673987]
 [-0.22673589 -2.20977142 -0.43332947  1.17846599]]
[[ 1.01728634  1.51464919 -0.24714715 -0.54425527]
 [ 0.24253792 -0.83579983  0.41615418 -1.66673987]
 [-0.22673589 -2.20977142 -0.43332947  1.17846599]]


array([[ 1.01728634,  1.51464919, -0.24714715, -0.54425527],
       [ 0.24253792, -0.83579983,  0.41615418, -1.66673987],
       [-0.22673589, -2.20977142, -0.43332947,  1.17846599]])

In [26]:
np.savetxt("sample2.txt", a, delimiter = ",")

In [31]:
# e = np.loadtxt("sample2.txt")
e = np.loadtxt("sample2.txt", delimiter = ",")
e

array([[ 0.6798412 ,  0.01410413,  1.66696495,  2.08897898],
       [ 1.86969266, -0.52541878, -0.6589359 , -0.2723675 ],
       [ 1.30107773,  0.34341242, -1.16941115,  0.08349848]])

In [2]:
import numpy as np

sam1 = np.array([2024, 4, 4])
sam2 = np.array([2003, 3, 12])
sam_final = np.r_["0, 2", sam1, sam2]

np.savetxt("Important.txt", sam_final, fmt = "%d")
np.loadtxt("Important.txt")

array([[2024.,    4.,    4.],
       [2003.,    3.,   12.]])

In [6]:
np.savetxt("sample3.txt", a, fmt = "%.2e")
np.savetxt("sample4.txt", a, fmt = "%.2f")

In [12]:
np.savetxt("sample5.txt", a, fmt = "%.3e", header = "this is a header", footer = "this is a footer")
np.savetxt("sample6.txt", a, fmt = "%.3e", 
           header = "This is a header", footer = "this is a footer", comments = ">>>")
np.loadtxt("sample6.txt", comments = ">>>")

array([[ 1.017 ,  1.515 , -0.2471, -0.5443],
       [ 0.2425, -0.8358,  0.4162, -1.667 ],
       [-0.2267, -2.21  , -0.4333,  1.178 ]])

In [20]:
print(np.loadtxt("sample4.txt", usecols = (0, 2)))
np.loadtxt("sample4.txt", skiprows = 1)

[[ 1.02 -0.25]
 [ 0.24  0.42]
 [-0.23 -0.43]]


array([[ 0.24, -0.84,  0.42, -1.67],
       [-0.23, -2.21, -0.43,  1.18]])

In [35]:
np.loadtxt("foo.csv", dtype = [("col0", "i8"), 
                               ("col1", "S10"), 
                               ("col2", "f8"), 
                               ("col3", "S10")])

array([(18, b'female', 154.1, b'No'), (21, b'male', 172.3, b'Yes'),
       (22, b'female', 160.8, b'Yes'), (23, b'male', 180.1, b'Yes'),
       (25, b'female', 145. , b'No')],
      dtype=[('col0', '<i8'), ('col1', 'S10'), ('col2', '<f8'), ('col3', 'S10')])

In [25]:
np.loadtxt("foo.csv", dtype = [("col0", "i8"), 
                               ("col1", "S10"), 
                               ("col2", "f8"), 
                               ("col3", "S10")], unpack = True)

[array([18, 21, 22, 23, 25], dtype=int64),
 array([b'female', b'male', b'female', b'male', b'female'], dtype='|S10'),
 array([154.1, 172.3, 160.8, 180.1, 145. ]),
 array([b'No', b'Yes', b'Yes', b'Yes', b'No'], dtype='|S10')]

In [29]:
age, gender, tall, driver_license = np.loadtxt("foo.csv", dtype = [("col0", "i8"), 
                               ("col1", "S10"), 
                               ("col2", "f8"), 
                               ("col3", "S10")], unpack = True)
print(age)
print(gender)
print(tall)
driver_license

[18 21 22 23 25]
[b'female' b'male' b'female' b'male' b'female']
[154.1 172.3 160.8 180.1 145. ]


array([b'No', b'Yes', b'Yes', b'Yes', b'No'], dtype='|S10')

In [4]:
import numpy as np

def driver_license(str):
    if str == b"Yes":
        return 1
    else:
        return -1
    
def gender(str):
    if str == b"male":
        return 1
    else:
        return -1
    
np.loadtxt("foo.csv", converters = {1: gender, 
                                    3: driver_license})

array([[ 18. ,  -1. , 154.1,  -1. ],
       [ 21. ,   1. , 172.3,   1. ],
       [ 22. ,  -1. , 160.8,   1. ],
       [ 23. ,   1. , 180.1,   1. ],
       [ 25. ,  -1. , 145. ,  -1. ]])

## 2-24 建立隨機亂數的陣列-random模組

In [1]:
import numpy as np

print(np.random.rand())
print(np.random.randint(10))
print(np.random.rand(2, 3))
np.random.randint(10, size = (2, 3))

0.8388159149610774
1
[[0.28509646 0.55301128 0.31365814]
 [0.63796902 0.62892784 0.2568477 ]]


array([[5, 5, 7],
       [3, 2, 6]])

In [18]:
print(np.random.randint(5, 10, size = 10))
(10 - 5) * np.random.rand(10) + 5

[5 9 8 9 9 9 8 8 7 8]


array([5.02171151, 9.13619466, 6.5397231 , 8.58297968, 8.31269555,
       7.96621685, 9.80860451, 8.24020857, 5.51241531, 9.45959625])

In [26]:
np.random.seed(seed = 21)
print(np.random.rand())
np.random.seed(21)
print(np.random.rand())
np.random.seed(10)
print(np.random.rand(20))
np.random.seed(23)
print(np.random.rand(20))
np.random.seed(10)
print(np.random.rand(20))
np.random.seed(23)
np.random.rand(20)

0.04872488080912729
0.04872488080912729
[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578]
[0.51729788 0.9469626  0.76545976 0.28239584 0.22104536 0.68622209
 0.1671392  0.39244247 0.61805235 0.41193009 0.00246488 0.88403218
 0.88494754 0.30040969 0.58958187 0.97842692 0.84509382 0.06507544
 0.29474446 0.28793444]
[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578]


array([0.51729788, 0.9469626 , 0.76545976, 0.28239584, 0.22104536,
       0.68622209, 0.1671392 , 0.39244247, 0.61805235, 0.41193009,
       0.00246488, 0.88403218, 0.88494754, 0.30040969, 0.58958187,
       0.97842692, 0.84509382, 0.06507544, 0.29474446, 0.28793444])

In [42]:
a = ["Python", "Ruby", "Java", "JavaScript", "PHP"]
print(np.random.choice(a, 3))
print(np.random.choice(a, 5, replace = False))
print(np.random.choice(a, 20, p = [0.8, 0.05, 0.05, 0.05, 0.05]))
np.random.choice(5, 10)

['Java' 'Ruby' 'PHP']
['JavaScript' 'Ruby' 'Java' 'Python' 'PHP']
['Python' 'PHP' 'Python' 'Python' 'Python' 'Python' 'Python' 'JavaScript'
 'Python' 'Python' 'Python' 'Python' 'Python' 'Python' 'Python' 'Python'
 'Python' 'Python' 'Python' 'Python']


array([4, 4, 0, 2, 3, 4, 2, 1, 3, 3])

In [46]:
a = np.arange(10)
print(a)
np.random.shuffle(a)
a

[0 1 2 3 4 5 6 7 8 9]


array([3, 5, 7, 1, 6, 8, 4, 2, 0, 9])